import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const css = readFileSync(resolve(process.cwd(), 'src/styles.css'), 'utf8');

function rule(selector: string): string {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = css.match(new RegExp(`${escapedSelector}\\s*\\{([\\s\\S]*?)\\}`, 'm'));
  return match?.[1] ?? '';
}

function rules(selector: string): string {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return Array.from(css.matchAll(new RegExp(`${escapedSelector}\\s*\\{([\\s\\S]*?)\\}`, 'gm')))
    .map((match) => match[1])
    .join('\n');
}

function keyframes(name: string): string {
  const marker = `@keyframes ${name}`;
  const start = css.indexOf(marker);
  if (start < 0) return '';
  const next = css.indexOf('@keyframes', start + marker.length);
  return css.slice(start, next < 0 ? undefined : next);
}

describe('mobile layout CSS', () => {
  it('keeps formal live-room videos letterboxed while preserving immersive home previews', () => {
    expect(rule('.live-video')).toContain('object-fit: contain');
    expect(rule('.digital-human-video')).toContain('object-fit: contain');
    expect(rule('.discover-video')).toContain('object-fit: cover');
  });

  it('uses one continuous bottom-tab background and highlights only active text/icons', () => {
    expect(css).toContain('--bottom-tab-height');
    expect(css).toContain('--app-shell-border-width');
    expect(rule('.bottom-tab-frame')).toContain('position: fixed');
    expect(rule('.bottom-tab-frame')).toContain('left: calc((100vw - min(100vw, var(--app-shell-max-width))) / 2 + var(--app-shell-border-width))');
    expect(rule('.bottom-tab-frame')).toContain('right: calc((100vw - min(100vw, var(--app-shell-max-width))) / 2 + var(--app-shell-border-width))');
    expect(rule('.bottom-tabs')).toContain('gap: 0');
    expect(rule('.bottom-tabs')).toContain('width: 100%');
    expect(rule('.bottom-tabs')).not.toContain('position: fixed');
    expect(rule('.bottom-tabs')).not.toContain('background: transparent');
    expect(rule('.bottom-tabs button')).toContain('background: transparent');
    expect(rule('.bottom-tabs button')).toContain('border-radius: 0');
    expect(rule('.bottom-tabs button.is-active')).not.toContain('background:');
    expect(rule('.tab-shell.is-home-tab .bottom-tabs')).toContain('background: rgba(5, 7, 13, 0.94)');
    expect(rule('.tab-shell.is-home-tab .bottom-tabs button')).toContain('color: rgba(255, 255, 255, 0.64)');
    expect(rule('.tab-shell.is-home-tab .bottom-tabs button.is-active')).toContain('color: #fff');
  });

  it('compresses the home preview lot strip and uses the transparent white live-entry button', () => {
    expect(rule('.discover-copy')).toContain('left: 16px');
    expect(rule('.discover-copy')).toContain('max-width: none');
    expect(rule('.discover-lot')).toContain('grid-template-columns: 35px minmax(0, 1fr) auto auto');
    expect(rule('.discover-lot')).toContain('justify-self: center');
    expect(rule('.discover-lot')).toContain('width: 100%');
    expect(rule('.discover-lot')).toContain('min-height: 44px');
    expect(rule('.discover-lot .visual-placeholder,\n.discover-lot img')).toContain('width: 35px');
    expect(rule('.discover-lot .visual-placeholder')).toContain('min-height: 0');
    expect(rule('.discover-lot .visual-placeholder small')).toContain('display: none');
    expect(rule('.discover-lot-status.is-running')).toContain('background: #ef4444');
    expect(rule('.discover-lot-status.is-upcoming')).toContain('border: 1px solid rgba(239, 68, 68, 0.34)');
    expect(rule('.discover-lot-schedule')).toContain('grid-column: 2 / -1');
    expect(rule('.discover-lot-schedule')).toContain('font-size: 11px');
    expect(rule('.discover-slide .discover-enter-button.adm-button')).toContain('background: rgba(255, 255, 255, 0.05)');
    expect(rule('.discover-slide .discover-enter-button.adm-button')).toContain('border: 1px solid rgba(255, 255, 255, 0.7)');
    expect(rule('.discover-slide .discover-enter-button.adm-button')).toContain('font-family: "Microsoft YaHei UI Light", "Microsoft YaHei", sans-serif');
    expect(rule('.discover-slide .discover-enter-button.adm-button')).toContain('font-weight: 300');
  });

  it('renders the home preview watcher count without a border', () => {
    expect(rules('.discover-watcher-count')).toContain('background: transparent');
    expect(rules('.discover-watcher-count')).not.toContain('border:');
  });

  it('uses the reference-style live-room header layout', () => {
    expect(css).toContain('--live-auction-action-width: clamp(112px, 30vw, 132px)');
    expect(rule('.live-header')).toContain('display: flex');
    expect(rule('.live-header')).toContain('padding: 6px 10px 0');
    expect(rule('.live-header')).toContain('z-index: 30');
    expect(rule('.live-back')).toContain('width: 28px');
    expect(rule('.live-back')).toContain('height: 28px');
    expect(rule('.live-back')).toContain('background: transparent');
    expect(rule('.live-shop')).toContain('grid-template-columns: 28px minmax(0, 1fr) auto');
    expect(rule('.live-shop')).toContain('width: fit-content');
    expect(rule('.live-shop')).toContain('max-width: min(66vw, 260px)');
    expect(rule('.live-shop')).toContain('background: rgba(31, 36, 49, 0.82)');
    expect(rule('.live-shop')).toContain('border-radius: 999px');
    expect(rule('.live-shop-logo')).toContain('width: 28px');
    expect(rule('.live-shop strong')).toContain('font-size: 12px');
    expect(rules('.live-shop span')).toContain('font-size: 9px');
    expect(rule('.live-follow-pill')).toContain('height: 24px');
    expect(rule('.live-follow-pill')).toContain('background: linear-gradient(135deg, #ff72a5 0%, #f44f92 100%)');
    expect(rule('.live-header-bidders')).toBe('');
    expect(rule('.live-header-bidder')).toBe('');
    expect(rule('.live-watcher-count')).toContain('background: transparent');
    expect(rule('.live-watcher-count')).toContain('opacity: 0.7');
    expect(rule('.live-watcher-count')).not.toContain('border:');
    expect(rule('.live-header-watchers')).toContain('min-width: 38px');
    expect(css).toContain('@media (max-width: 360px)');
    expect(rules('.live-header-bidders')).toBe('');
    expect(rule('.live-voice-permission')).toContain('z-index: 34');
    expect(rule('.live-voice-permission')).toContain('grid-template-columns: minmax(0, 1fr) auto');
    expect(rule('.live-voice-permission-button')).toContain('background: #fdb022');
    expect(rules('.live-voice-permission-button')).toContain('width: 100%');
  });

  it('keeps live-room bottom controls compact', () => {
    expect(css).toContain('--live-auction-action-width: clamp(112px, 30vw, 132px)');
    expect(rule('.live-comment-input-row')).toContain('grid-template-columns: 36px minmax(0, 1fr) 36px var(--live-auction-action-width)');
    expect(rule('.live-comment-input-row.is-collapsed')).toContain('display: flex');
    expect(rule('.live-comment-list')).toContain('width: min(72vw, 280px)');
    expect(rule('.live-comment-list')).toContain('max-height: min(30vh, 176px)');
    expect(rule('.live-comment-item')).toContain('display: flex');
    expect(rule('.live-comment-item')).toContain('align-items: flex-start');
    expect(rule('.live-comment-item span')).toContain('overflow-wrap: anywhere');
    expect(rule('.live-comment-item span')).toContain('white-space: normal');
    expect(rule('.comment-toggle-button,\n.comment-composer-send-button,\n.comment-list-button')).toContain('width: 36px');
    expect(rule('.comment-toggle-button.is-floating')).toContain('background: transparent');
    expect(rule('.comment-toggle-button.is-floating')).toContain('border: 0');
    expect(rule('.comment-input-trigger')).toContain('border-radius: 999px');
    expect(rule('.comment-like-button')).toContain('background: transparent');
    expect(rule('.comment-like-button')).toContain('border: 0');
    expect(rule('.comment-like-button')).toContain('box-shadow: none');
    expect(rule('.comment-like-button')).toContain('overflow: visible');
    expect(rule('.comment-like-button img')).toContain('filter: brightness(0) invert(1)');
    expect(rule('.comment-like-button.is-liked img')).toContain('hue-rotate(335deg)');
    expect(rule('.comment-like-burst')).toContain('inset: -10px');
    expect(rule('.comment-like-burst span')).toContain('width: 5px');
    expect(rule('.comment-like-burst span')).toContain('height: 5px');
    expect(rule('.comment-like-burst span')).toContain('--particle-color: #ff3158');
    expect(rule('.comment-like-burst span')).toContain('background: var(--particle-color)');
    expect(rule('.comment-like-burst span')).toContain('--particle-mid-distance');
    expect(rule('.comment-like-burst span')).toContain('animation: like-particle-burst');
    expect(rule('.comment-like-burst span')).toContain('cubic-bezier(0.06, 0.88, 0.18, 1)');
    expect(rule('.comment-like-burst span:nth-child(2)')).toContain('--particle-color: #ffd43b');
    expect(rule('.comment-like-burst span:nth-child(3)')).toContain('--particle-color: #3aa7ff');
    expect(rule('.comment-like-burst span:nth-child(15)')).toContain('--particle-angle: 336deg');
    expect(css).toContain('@keyframes like-particle-burst');
    expect(css).toContain('translateY(calc(-1 * var(--particle-mid-distance)))');
    expect(rule('.live-comment-panel.is-composing')).toContain('z-index: 45');
    expect(rule('.live-comment-compose-dismiss')).toContain('z-index: 1');
    expect(rule('.live-comment-compose-dismiss')).toContain('inset: 0 0 calc(54px + env(safe-area-inset-bottom))');
    expect(rule('.live-comment-composer')).toContain('grid-template-columns: minmax(0, 1fr) 56px');
    expect(rule('.live-comment-composer')).toContain('z-index: 2');
    expect(rule('.live-comment-composer textarea')).toContain('min-height: 36px');
    expect(rule('.live-comment-composer textarea')).toContain('max-height: 118px');
    expect(rule('.live-comment-composer textarea')).toContain('line-height: 20px');
    expect(rule('.comment-composer-send-button')).toContain('width: 56px');
    expect(rule('.comment-composer-send-button')).toContain('height: 36px');
    expect(rule('.comment-composer-send-button')).toContain('background: #f9a7bd');
    expect(rules('.comment-list-button')).toContain('width: var(--live-auction-action-width)');
    expect(rules('.comment-list-button')).toContain('background: linear-gradient(135deg, #ff7a18 0%, #ff2d55 100%)');
    expect(rule('.auction-float-card')).toContain('width: var(--live-auction-action-width)');
    expect(rule('.auction-float-card')).toContain('bottom: calc(66px + env(safe-area-inset-bottom))');
    expect(rule('.lot-result-card')).toContain('height: 128px');
    expect(rule('.lot-result-card')).toContain('max-height: 128px');
    expect(rule('.lot-result-card')).toContain('padding: 0 12px 0 0');
    expect(rule('.lot-result-card')).toContain('overflow: hidden');
    expect(rule('.lot-result-card')).toContain('position: relative');
    expect(rule('.lot-result-card')).toContain('cursor: pointer');
    expect(rule('.lot-media-wrap')).toContain('width: 118px');
    expect(rule('.lot-media-wrap')).toContain('height: 100%');
    expect(rule('.lot-media-wrap')).toContain('position: relative');
    expect(rule('.lot-result-card .result-media')).toContain('width: 100%');
    expect(rule('.lot-result-card .result-media')).toContain('height: 100%');
    expect(rule('.lot-result-card .result-media')).toContain('border-radius: 8px');
    expect(rule('.lot-result-card h3')).toContain('margin: 0 0 5px');
    expect(rule('.lot-result-card h3')).toContain('font-size: 16px');
    expect(rule('.lot-status-line')).toContain('position: absolute');
    expect(rule('.lot-status-line')).toContain('bottom: 10px');
    expect(rule('.lot-result-card .status-badge')).toContain('background: rgba(0, 0, 0, 0.58)');
    expect(rule('.lot-info')).toContain('grid-row: 1 / 3');
    expect(rule('.lot-info')).toContain('padding: 14px 0 12px');
    expect(rule('.lot-merchant-link')).toContain('align-self: flex-start');
    expect(rule('.lot-merchant-link')).toContain('color: #1677ff');
    expect(rule('.lot-merchant-link')).toContain('font-size: 12px');
    expect(rule('.lot-merchant-link')).toContain('background: transparent');
    expect(rule('.lot-merchant-link')).toContain('border: 0');
    expect(rule('.lot-result-card .lot-price-line')).toContain('margin-top: auto');
    expect(rule('.lot-schedule-line')).toContain('width: fit-content');
    expect(rule('.lot-schedule-line')).toContain('background: #fff7ed');
    expect(rule('.orders-page')).toContain('display: flex');
    expect(rule('.orders-page')).toContain('overflow: hidden');
    expect(rule('.orders-tab-row')).toContain('flex: 0 0 auto');
    expect(rule('.orders-page > .result-list')).toContain('overflow-y: auto');
    expect(rule('.orders-page > .result-list')).toContain('align-content: start');
    expect(rule('.orders-page > .result-list')).toContain('grid-auto-rows: max-content');
  });

  it('docks the live ranking rail under the follow button with a low-alpha background', () => {
    expect(rule('.live-ranking-rail')).toContain('position: absolute');
    expect(rule('.live-ranking-rail')).toContain('right: 0');
    expect(rule('.live-ranking-rail')).toContain('top: 58px');
    expect(rule('.live-ranking-rail')).toContain('background: rgba(0, 0, 0, 0.2)');
    expect(rule('.live-ranking-rail')).toContain('--live-ranking-toggle-width: 20px');
    expect(rule('.live-ranking-rail')).toContain('--live-ranking-price-width: 64px');
    expect(rule('.live-ranking-toggle')).toContain('left: calc(-1 * var(--live-ranking-toggle-width))');
    expect(rule('.live-ranking-toggle')).toContain('height: 64px');
    expect(rule('.live-ranking-toggle')).toContain('writing-mode: horizontal-tb');
    expect(rule('.live-ranking-toggle')).toContain('border: 1px solid rgba(255, 255, 255, 0.46)');
    expect(rule('.live-ranking-toggle b')).toContain('writing-mode: vertical-rl');
    expect(rule('.live-ranking-rail.is-collapsed')).toContain('transform: translateX(100%)');
    expect(rule('.live-ranking-panel')).toContain('min-height: 0');
    expect(rule('.live-ranking-panel')).toContain('grid-auto-rows: max-content');
    expect(rule('.live-ranking-panel')).toContain('align-content: start');
    expect(rule('.live-ranking-board-viewport')).toContain('position: relative');
    expect(rule('.live-ranking-board-viewport')).toContain('overflow: hidden');
    expect(rule('.live-ranking-row')).toContain('grid-template-columns: 19px 22px minmax(0, 1fr) var(--live-ranking-price-width)');
    expect(rule('.live-ranking-title')).toContain('justify-content: center');
    expect(rule('.live-ranking-price')).toContain('color: #ff4d5f');
    expect(rule('.live-ranking-price')).toContain('justify-self: center');
    expect(rule('.live-ranking-price')).toContain('width: var(--live-ranking-price-width)');
    expect(rule('.live-ranking-price')).toContain('text-align: center');
    expect(rule('.live-ranking-price.is-leading-price')).toContain('font-size: 12px');
    expect(rule('.live-ranking-row.is-leading .live-ranking-name')).toContain('color: #ffd45f');
    expect(rule('.live-ranking-rank.is-plain')).toContain('background: transparent');
    expect(rule('.live-ranking-rank.is-plain')).not.toContain('border:');
    expect(rule('.live-ranking-divider')).toContain('margin: 0 2px');
    expect(rule('.live-ranking-current-row')).toContain('min-height: 28px');
    expect(rule('.live-ranking-current-row')).toContain('padding-top: 0');
    expect(rule('.live-ranking-row.is-moving-target')).toContain('animation: ranking-target-reveal var(--ranking-duration-ms');
    expect(css).toContain('.live-ranking-row.is-moving-target > .live-ranking-name');
    expect(css).toContain('.live-ranking-row.is-moving-target > .live-ranking-price');
    expect(css).toContain('opacity: 0');
    expect(rule('.live-ranking-exit-row')).toContain('animation: ranking-row-exit-divider var(--ranking-duration-ms');
    expect(rule('.live-ranking-exit-row')).not.toContain('grid-template-columns:');
    expect(rule('.live-ranking-exit-row')).not.toContain('font-size:');
    expect(rule('.live-ranking-exit-row')).not.toContain('filter:');
    expect(rule('.live-ranking-ghost')).toContain('top: var(--ranking-to-y');
    expect(rule('.live-ranking-ghost')).toContain('--ranking-pop-scale: 1.12');
    expect(rule('.live-ranking-ghost.is-self-bid')).toContain('--ranking-pop-scale: 1.3');
    expect(rule('.live-ranking-ghost.is-divider-to-first')).toContain('animation: ranking-divider-to-first var(--ranking-duration-ms');
    expect(rule('.live-ranking-ghost.is-current-row-to-first')).toContain('animation: ranking-current-row-to-first var(--ranking-duration-ms');
    expect(css).toContain('@keyframes ranking-price-update');
    expect(css).toContain('@keyframes ranking-top-slot-to-first');
    expect(css).toContain('@keyframes ranking-divider-to-first');
    expect(css).toContain('@keyframes ranking-current-row-to-first');
    expect(css).toContain('@keyframes ranking-row-exit-divider');
    expect(keyframes('ranking-row-exit-divider')).toContain('transform: translate3d(0, calc(var(--ranking-exit-to-y, 0px) - var(--ranking-exit-from-y, 0px)), 0)');
    expect(keyframes('ranking-row-exit-divider')).toContain('99%');
    expect(keyframes('ranking-row-exit-divider')).not.toContain('opacity: 0.72');
    expect(keyframes('ranking-row-exit-divider')).not.toContain('scale(');
  });

  it('animates live room sheets from the backdrop and bottom panel', () => {
    expect(rule('.sheet-backdrop')).toContain('z-index: 110');
    expect(rule('.sheet-backdrop')).toContain('--sheet-enter-duration-ms: 250ms');
    expect(rule('.sheet-backdrop')).toContain('--sheet-exit-duration-ms: 150ms');
    expect(rule('.sheet-backdrop')).toContain('--sheet-easing: linear');
    expect(rule('.sheet-backdrop')).not.toContain('animation: sheet-backdrop-in');
    expect(rule('.sheet-backdrop::before')).toContain('animation: sheet-backdrop-in var(--sheet-enter-duration-ms) var(--sheet-easing) both');
    expect(rule('.sheet-backdrop.is-closing::before')).toContain('animation: sheet-backdrop-out var(--sheet-exit-duration-ms) var(--sheet-easing) forwards');
    expect(rule('.sheet-layer')).toContain('z-index: 110');
    expect(rule('.sheet-layer')).toContain('background: transparent');
    expect(rule('.sheet-layer.is-closing .bottom-sheet')).toContain('animation: sheet-slide-down var(--sheet-exit-duration-ms) var(--sheet-easing) forwards');
    expect(rule('.bottom-sheet')).toContain('animation: sheet-slide-up var(--sheet-enter-duration-ms) var(--sheet-easing) both');
    expect(rule('.bottom-sheet')).toContain('will-change: transform');
    expect(rule('.sheet-backdrop.is-closing .bottom-sheet')).toContain('animation: sheet-slide-down var(--sheet-exit-duration-ms) var(--sheet-easing) forwards');
    expect(rule('.lot-list-sheet')).toContain('height: 70dvh');
    expect(rule('.lot-list-sheet')).toContain('max-height: 70dvh');
    expect(rule('.lot-list')).toContain('height: calc(100% - 52px)');
    expect(rule('.lot-list')).toContain('align-content: start');
    expect(rule('.lot-list')).toContain('max-height: none');
    expect(rule('.lot-list')).toContain('overflow-y: auto');
    expect(rule('.lot-row')).toContain('--lot-thumb-size: 92px');
    expect(rule('.lot-row')).toContain('grid-template-columns: var(--lot-thumb-size) minmax(0, 1fr) auto');
    expect(rule('.lot-thumb-frame')).toContain('position: relative');
    expect(rule('.lot-thumb-frame')).toContain('width: var(--lot-thumb-size)');
    expect(rule('.lot-thumb-frame')).toContain('height: var(--lot-thumb-size)');
    expect(rule('.lot-sequence')).toContain('position: absolute');
    expect(rule('.lot-sequence')).toContain('min-width: 18px');
    expect(rule('.lot-sequence')).toContain('height: 18px');
    expect(rule('.lot-sequence')).toContain('font-size: 9px');
    expect(rule('.lot-sequence')).toContain('background: rgba(15, 23, 42, 0.5)');
    expect(rule('.lot-sequence')).toContain('color: #fff');
    expect(rule('.lot-action-button.is-look')).toContain('background: #fff');
    expect(rule('.lot-action-button.is-disabled')).toContain('background: #e5e7eb');
    expect(rule('.detail-sheet')).toContain('height: 75dvh');
    expect(rule('.detail-sheet')).toContain('max-height: 75dvh');
    expect(rule('.detail-sheet')).toContain('display: flex');
    expect(rule('.detail-sheet')).toContain('overflow: hidden');
    expect(rule('.detail-sheet-header')).toContain('position: sticky');
    expect(rule('.detail-header-title')).toContain('display: flex');
    expect(rule('.detail-header-title')).toContain('align-items: center');
    expect(rule('.lot-gallery')).toContain('overflow: hidden');
    expect(rule('.lot-gallery-media-button')).toContain('touch-action: pan-y');
    expect(rule('.lot-gallery-track')).toContain('transition: transform 220ms ease');
    expect(rule('.lot-gallery-track.is-dragging,\n.lot-gallery-track.is-resetting')).toContain('transition: none');
    expect(rule('.lot-gallery-slide')).toContain('position: relative');
    expect(rule('.lot-gallery-slide')).toContain('overflow: hidden');
    expect(rule('.lot-gallery-slide img')).toContain('position: absolute');
    expect(rule('.lot-gallery-slide img')).toContain('top: 50%');
    expect(rule('.lot-gallery-slide img')).toContain('width: 100%');
    expect(rule('.lot-gallery-slide img')).toContain('height: auto');
    expect(rule('.lot-gallery-slide img')).toContain('transform: translateY(-50%)');
    expect(rule('.lot-gallery-slide img')).not.toContain('object-fit: cover');
    expect(rule('.lot-gallery-slide img')).toContain('object-position: center center');
    expect(rule('.image-viewer-backdrop')).toContain('position: fixed');
    expect(rule('.image-viewer-backdrop')).toContain('z-index: 1200');
    expect(rule('.image-viewer-image')).toContain('touch-action: none');
    expect(rule('.image-viewer-image img')).toContain('transform: translate3d(var(--viewer-offset-x, 0px), var(--viewer-offset-y, 0px), 0) scale(var(--viewer-scale, 1))');
    expect(rule('.image-viewer-reset')).toContain('left: 50%');
    expect(rule('.image-viewer-reset')).toContain('bottom: calc(112px + env(safe-area-inset-bottom))');
    expect(rule('.image-viewer-reset')).toContain('min-width: 96px');
    expect(rule('.image-viewer-reset')).toContain('height: 40px');
    expect(rule('.image-viewer-reset')).toContain('font-size: 16px');
    expect(rule('.image-viewer-reset')).toContain('background: rgba(31, 36, 49, 0.52)');
    expect(rule('.image-viewer-reset')).toContain('border-radius: 999px');
    expect(rule('.detail-scroll-body')).toContain('overflow-y: auto');
    expect(rule('.detail-sticky-actions')).toContain('position: sticky');
    expect(rule('.detail-rule-grid .metric')).toContain('justify-items: center');
    expect(rule('.detail-ranking-header')).toContain('justify-content: center');
    expect(rule('.detail-ranking-list')).toContain('max-height: calc(var(--detail-ranking-visible-rows) * 36px)');
    expect(rule('.detail-ranking-list')).toContain('transition: max-height 220ms ease, opacity 220ms ease');
    expect(rule('.detail-ranking-panel.is-expanded')).toContain('--detail-ranking-visible-rows: 8');
    expect(rule('.detail-ranking-actions')).toContain('justify-content: center');
    expect(rule('.detail-ranking-price.is-first')).toContain('color: #dc2626');
    expect(rule('.record-card.is-highlighted')).toContain('box-shadow: 0 0 0 2px rgba(255, 90, 102, 0.18)');
    expect(css).toContain('@keyframes sheet-slide-up');
    expect(keyframes('sheet-slide-up')).toContain('transform: translateY(100%)');
    expect(css).toContain('@keyframes sheet-slide-down');
    expect(keyframes('sheet-slide-down')).toContain('transform: translateY(100%)');
    expect(css).toContain('@media (prefers-reduced-motion: reduce)');
  });

  it('styles quick bid countdown segments and the filled leader badge', () => {
    expect(rule('.quick-bid-countdown-display')).toContain('display: inline-flex');
    expect(rule('.quick-bid-countdown-unit')).toContain('background: #ff8a00');
    expect(rule('.quick-bid-countdown-unit')).toContain('min-width: 34px');
    expect(rule('.quick-bid-countdown-unit.is-milliseconds')).toContain('min-width: 42px');
    expect(rule('.quick-bid-countdown-unit.is-milliseconds')).toContain('background: #fb7185');
    expect(rule('.quick-bid-countdown-separator')).toContain('color: #f97316');
    expect(rule('.quick-bid-countdown-separator.is-milliseconds')).toContain('color: #fb7185');
    expect(rule('.quick-bid-leader-badge')).toContain('background: #ffe3ec');
    expect(rule('.quick-bid-leader-badge')).toContain('border-radius: 999px');
    expect(rule('.quick-bid-leader-avatar')).toContain('background: linear-gradient(135deg, #7da4ff 0%, #6d5dfc 100%)');
  });

  it('shows and sinks auction floating cards into the goods button', () => {
    expect(rule('.auction-float-card.is-entering')).toContain('animation: auction-card-rise 380ms cubic-bezier(0.22, 1, 0.36, 1) forwards');
    expect(rule('.auction-float-card.is-ended .float-card-action')).toContain('background: #98a2b3');
    expect(rule('.auction-float-card.is-ended .float-card-action')).toContain('cursor: not-allowed');
    expect(rule('.auction-float-card.is-leaving')).toContain('animation: auction-card-sink 380ms cubic-bezier(0.22, 1, 0.36, 1) forwards');
    expect(rule('.auction-float-dismiss')).toContain('background: transparent');
    expect(rule('.auction-float-dismiss')).toContain('border: 0');
    expect(css).toContain('@keyframes auction-card-rise');
    expect(css).toContain('@keyframes auction-card-sink');
  });

  it('styles payment animation and receipt confirmation as mobile-first controls', () => {
    expect(rule('.payment-animation')).toContain('place-items: center');
    expect(rule('.payment-spinner')).toContain('animation: payment-spinner');
    expect(rule('.payment-flow')).toContain('animation: payment-flow');
    expect(rule('.payment-animation.is-paid .payment-check')).toContain('animation: payment-check-draw');
    expect(rule('.logout-choice-backdrop,\n.receipt-confirm-backdrop')).toContain('align-items: end');
    expect(rule('.logout-choice-panel,\n.receipt-confirm-panel')).toContain('border-radius: 18px 18px 0 0');
    expect(rule('.receipt-confirm-lot span')).toContain('text-overflow: ellipsis');
    expect(rule('.logout-choice-actions .adm-button,\n.receipt-confirm-actions .adm-button')).toContain('min-height: 44px');
  });

  it('renders auction atmosphere alerts above all live-room UI without blocking touches', () => {
    expect(rule('.live-auction-alert-layer')).toContain('position: fixed');
    expect(rule('.live-auction-alert-layer')).toContain('z-index: 1400');
    expect(rule('.live-auction-alert-layer')).toContain('pointer-events: none');
    expect(rule('.live-auction-alert')).toContain('animation: auction-alert-pop');
    expect(rule('.live-auction-alert.is-outbid')).toContain('animation-name: auction-alert-shake');
    expect(rule('.live-auction-alert.is-won')).toContain('animation-name: auction-alert-win');
    expect(rule('.live-auction-alert-cannon.is-left')).toContain('animation: auction-alert-cannon-left');
    expect(rule('.live-auction-alert-cannon.is-right')).toContain('animation: auction-alert-cannon-right');
    expect(rule('.live-auction-alert-confetti-piece')).toContain('animation: auction-alert-confetti-left');
    expect(rule('.live-auction-alert-confetti-piece.is-right')).toContain('animation-name: auction-alert-confetti-right');
    expect(css).toContain('@keyframes auction-alert-pop');
    expect(css).toContain('@keyframes auction-alert-shake');
    expect(css).toContain('@keyframes auction-alert-win');
    expect(css).toContain('@keyframes auction-alert-cannon-left');
    expect(css).toContain('@keyframes auction-alert-cannon-right');
    expect(css).toContain('@keyframes auction-alert-confetti-left');
    expect(css).toContain('@keyframes auction-alert-confetti-right');
  });

  it('styles the countdown pressure feedback through the global alert layer', () => {
    expect(css).not.toContain('.live-countdown-pressure');
    expect(rule('.live-auction-alert.is-countdown')).toContain('animation-duration: 1400ms');
    expect(rule('.live-auction-alert.is-countdown .live-auction-alert-card')).toContain('background: linear-gradient');
    expect(rule('.live-auction-alert.is-countdown .live-auction-alert-value')).toContain('font-size: clamp(58px, 18vw, 86px)');
    expect(rule('.live-auction-alert.is-countdown.is-warning .live-auction-alert-card')).toContain('animation: countdown-alert-pulse');
    expect(rule('.live-auction-alert.is-countdown.is-critical')).toContain('animation-name: auction-alert-shake');
    expect(rule('.live-auction-alert.is-countdown.is-critical .live-auction-alert-card')).toContain('animation: countdown-alert-critical');
    expect(rule('.live-auction-alert.is-countdown.is-extended .live-auction-alert-card')).toContain('animation: countdown-alert-extended');
    expect(rule('.auction-float-countdown.is-warning')).toContain('color: #ffb020');
    expect(rule('.auction-float-countdown.is-critical')).toContain('animation: float-countdown-critical');
    expect(rule('.quick-bid-countdown.is-warning .quick-bid-countdown-unit')).toContain('animation: quick-countdown-warning');
    expect(rule('.quick-bid-countdown.is-critical .quick-bid-countdown-unit')).toContain('animation: quick-countdown-critical');
    expect(css).toContain('@keyframes countdown-alert-pulse');
    expect(css).toContain('@keyframes countdown-alert-critical');
    expect(css).toContain('@keyframes countdown-alert-extended');
    expect(css).toContain('@keyframes float-countdown-critical');
    expect(css).toContain('@keyframes quick-countdown-warning');
    expect(css).toContain('@keyframes quick-countdown-critical');
  });
});
